### PR TITLE
Change comments from using `#` to using `//`

### PR DESCRIPTION
**Pull request by cburgdorf**
### What was wrong?

It seems like we have consensus that we don't want to continue to use `#` for comments but rather use `//` instead. This PR changes that.

### How was it fixed?

- Tiny change in the parser
- Updated code files
- Updated examples + docs
- Updated highlight.js on the website to use the custom `fe` highlighting that the docs already use

### CODE REVIEW

**Review by Y-Nak — APPROVED** [review]
Perfect!

**Comment by cburgdorf** [comment]
This actually needed to be rebased. It's now causing a CI failure on master. I'll send a follow up.

**Comment by cburgdorf** [comment]
> This actually needed to be rebased. It's now causing a CI failure on master. I'll send a follow up.

I pushed a fix directly to master :hand_over_mouth:  https://github.com/ethereum/fe/commit/9300ef4c9c9d4327a4551b036006cad2803e4abe

**Comment by Y-Nak** [comment]
Yeah, I missed that. Thanks for following up.

**Pull request merged**
