### PR TITLE
Support non base type items in structs #343

### PR DESCRIPTION
**Pull request by mjobuda**
### What was wrong?
Support non base type items in structs #343

### How was it fixed?
- added support for string type items in structs
- developed a unit test for this

### To-Do
- add support for other types
- refactor duplicated code in match expression in pub fn struct_def
- check this field_offset thing(I started to read https://docs.soliditylang.org/en/develop/internals/layout_in_storage.html but am not sure about this)

### CODE REVIEW

**Comment by sbillig** [comment]
@mjobuda Small request: could you rebase your relevant commits onto a branch that tracks ethereum/fe/master? It would be nicer to review these PRs if there weren't unrelated commits included. It's not a big deal, because the gh "Files changed" view is clean, but for more complicated changes, I often pull down PRs and step through the individual commits in my editor.

To be clear, this is a very minor thing and I'm still happy to review contributions if the commit history isn't clean.

**Comment by mjobuda** [comment]
@sbillig I'd love to! 
Can you give me some instructions on how to 
"rebase my relevant commits onto a branch that tracks ethereum/fe/master?".
Is there a magic git command for this?

**Comment by cburgdorf** [comment]
>Can you give me some instructions on how to

Basically:

```
git fetch
git rebase origin/master
```

You might have to work through conflicts during rebase in which case you:

1. Resolve them
2. Stage the files (e.g. `git add .`)
3. Run `git rebase --continue`
4. Repeat from 1.) if needed until the rebase is done

Then you you push your branch again with the `-f` parameter (force push)

**Comment by mjobuda** [comment]
@cburgdorf i'm still not sure if i got it right, sorry but i don't get stuff like
https://stackoverflow.com/questions/9257533/what-is-the-difference-between-origin-and-upstream-on-github
What is the correct way to get the work done and not get into this kind of problems?
Should I clone from the master and then create my branch?
Or git branch --set-upstream-to=origin/master i193 ???
What are the proper steps to not run into this kind of problems.
I see still all my commits and have no idea what and how to do it to not get git come into my way.
Sorry, but I don't get git.
I have no idea how to get a clean working environment.
Whatever I do, I still have "This branch is 10 commits ahead of ethereum:master.".
Is there a simple way to get rid of this? 
Should I delete my fork?
If so how should I proceed to not have this git problems

**Comment by cburgdorf** [comment]
Ah, sorry, maybe I confused what `origin` is in your case. In fact, the term `origin` is heavily overloaded which is why I personally never use it. I use `me` to point to my own fork and `upstream` to point to the central repository that everyone uses to coordinate the work.

Let's try that again.

1. Run `git remote -v`

Does this only show `origin` and is that your own fork?

2. Run `git remote add upstream https://github.com/ethereum/fe.git` to add an `upstream` pointing to **this** repo.

3. Fetch the latest from `upstream` via `git fetch upstream`

4. Rebase `git rebase upstream/master`

You might have to work through conflicts during rebase in which case you:

I. Resolve them
II. Stage the files (e.g. `git add .`)
III. Run `git rebase --continue`
IV. Repeat from I.) if needed until the rebase is done

5. Then force push your branch into **your** fork via `git push -f origin <branchname>`

If that still doesn't work I'm happy to hop on a call with you or just feel free to join our team call today at 17:00 Berlin time :)

**Comment by sbillig** [comment]
I'm going to close this, as it seems to be abandoned (perhaps because I derailed it with git nonsense :grimacing:). @mjobuda, please don't hesitate to reopen this if you're still interested.

**Pull request closed without merging**
