### PR TITLE
Add support for pragma statement

### PR DESCRIPTION
**Pull request by cburgdorf**
### What was wrong?

As described in #361 developers need to have a way to express that a piece of code can only be compiled with a compiler where the version matches a given requirement.

### How was it fixed?

- Added support for `pragma` keyword in the parser
- Version requirement is parsed using the `semver` crate
- The Analyzer checks the compiler version against the version requirement and raises a `WrongCompilerError` if needed.

### CODE REVIEW

**Comment by sbillig** [comment]
More use cases for this:

```
`#![forbid(dynamic)] // disallow any code that prevents gas analysis
```

```
#[target(evm)]
fn deploy() -> Foo:
  return Foo::create2(1, 2)

#[target(ewasm)]
fn deploy() -> Foo:
  ...
```

**Comment by sbillig** [comment]
Sorry, I realize this discussion should have happened *before* you started implementing this. We can always change the syntax later, the important part is that we have the compiler version lock functionality.

**Comment by cburgdorf** [comment]
You are raising good points here. But as you say, we have enough time to change the syntax at a later point in time. My immediate focus is to make sure we support rejecting code that was written to be compiled with a different compiler version so I just followed soliditys `pragma <version-requirement>` syntax (where `<version-requirement>` is any semver range syntax that is also valid on `Cargo.toml` files).

**Review by sbillig — APPROVED** [review]
Looks great. It'd probably be good to have an analyzer error test of the version mismatch case.

**Comment by cburgdorf** [comment]
>It'd probably be good to have an analyzer error test of the version mismatch case.

Good point, added!

**Pull request merged**
